config/routes.rb
Qiwo::Application.routes.draw do
  
  
  
  get '/articulo/:nombre', to: 'blogs#show'
  get '/portada/:frontpage', to: 'blogs#frontpage'
  resources :blogs

  resources :mailtemplates

  resources :qiwo_cfdis

  match '/redpacks/allowGuide', :controller => 'redpacks', :action => 'allowGuide'
  resources :redpacks

  resources :qiwo_profiles

  resources :shipping_guides

  resources :nfc_requests

  resources :cfdi_apis

  match '/facturacions/populateRollBack', :controller => 'facturacions', :action => 'populateRollBack'
  match '/facturacions/execRollBack', :controller => 'facturacions', :action => 'execRollBack'
  resources :facturacions

  match '/telegrams/validateTelegram', :controller => 'telegrams', :action => 'validateTelegram'
  match '/telegrams/login', :controller => 'telegrams', :action => 'emailLogin'
  match '/telegrams/ping', :controller => 'telegrams', :action => 'ping'
  match '/telegrams/telegram_actions', :controller => 'telegrams', :action => 'telegram_actions'
  resources :telegrams

  resources :nfc_readers

  resources :print_facturas

  resources :qiwo_counters

  resources :sat_documents

  match '/qiwo_employees/asociadoBuscar', :controller => 'qiwo_employees', :action => 'lookInFacebookEmployees'
  match '/qiwo_employees/misEmpleados', :controller => 'qiwo_employees', :action => 'listEmployees'
  match '/qiwo_employees/contratarEmpleado', :controller => 'qiwo_employees', :action => 'assignEmployee'
  match '/qiwo_employees/despedirEmpleado', :controller => 'qiwo_employees', :action => 'fireEmployee'
  resources :qiwo_employees

  resources :qiwo_orders

  match '/sale_points/puntoDeVentaProducto', :controller => 'sale_points', :action => 'searchByProduct'
  match '/sale_points/puntoDeVentaSKU', :controller => 'sale_points', :action => 'searchBySKU'
  match '/sale_points/puntoDeVentaNuevaOrden', :controller => 'sale_points', :action => 'createNewOrder'
  match '/sale_points/puntoDeVentaItems', :controller => 'sale_points', :action => 'getOrderItems'
  match '/sale_points/puntoDeVentaAlterItems', :controller => 'sale_points', :action => 'addProductToOrder'
  match '/sale_points/puntoDeVentaAlterGetTax', :controller => 'sale_points', :action => 'getTaxAddons'
  match '/sale_points/puntoDeVentaAlterSetTax', :controller => 'sale_points', :action => 'setTaxAddons'
  match '/sale_points/puntoDeVentaCloseOrder', :controller => 'sale_points', :action => 'closeOrder'
  match '/sale_points/puntoDeVentaValidar', :controller => 'sale_points', :action => 'validateOrderPayment'
  match '/sale_points/puntoDeVentaCerrarCuenta', :controller => 'sale_points', :action => 'closeWithNoInvoice'
  match '/sale_points/fd_card', :controller => 'sale_points', :action => 'first_data_card'
  resources :sale_points

  resources :cartera_clientes

  resources :payments

  resources :qiwo_subscriptions

  match '/qiwo_user_subscriptions/paySubscription', :controller => 'qiwo_user_subscriptions', :action => 'paySubscription'
  match '/qiwo_user_subscriptions/incomingFromPaypal', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromPaypal'
  match '/gateway/incomingFromConekta', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromConekta'
  match '/gateway/incomingFromOpenPay', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromOpenPay'
  resources :qiwo_user_subscriptions

  match '/qiwo_tools/updateMerchantTools', :controller => 'qiwo_tools', :action => 'updateMerchantTools'
  resources :qiwo_tools

  

  resources :qiwo_measure_units

  match '/yo/sendMessageToAll', :controller => 'yo', :action => 'sendMessageToAll'
  match '/yo/getCalendar', :controller => 'yo', :action => 'getCalendar'
  match '/yo/qiwoLogOut', :controller => 'yo', :action => 'qiwoLogOut'
  match '/yo/createGuides', :controller => 'yo', :action => 'createGuides'
  match '/yo/reassignPlan', :controller => 'yo', :action => 'reassignPlan'
  match '/yo/reassignCFDI', :controller => 'yo', :action => 'reassignCFDI'
  match '/yo/qtinbo', :controller => 'yo', :action => 'qtinbo'
  get '/yo', to: redirect('/dashboard')
  get 'dashboard', to: 'yo#index'

  resources :qiwo_categories

  match '/suscribir/me', :controller => 'welcome', :action => 'suscribir'
  root :to => 'welcome#index'

  resources :qiwo_item_tags

  resources :qiwo_tags

  resources :qiwo_product_categories

  resources :qiwo_coupons

  resources :qiwo_ranks

  resources :qiwo_reviews

  match '/qiwo_products/applyDiscount', :controller => 'qiwo_products', :action => 'applyDiscount'
  match '/qiwo_products/compartir', :controller => 'qiwo_products', :action => 'shareProduct'
  match '/qiwo_products/getProductsAsToken', :controller => 'qiwo_products', :action => 'getProductsAsToken'
  resources :qiwo_products

  resources :qiwo_images

  match '/qiwo_log_karts/oxxoPayment', :controller => 'qiwo_log_karts', :action => 'oxxoPayment'
  match '/qiwo_log_karts/banortePayment', :controller => 'qiwo_log_karts', :action => 'banortePayment'
  match '/qiwo_log_karts/thirdPartySale', :controller => 'qiwo_log_karts', :action => 'thirdPartySale'
  match '/qiwo_log_karts/basicPayments', :controller => 'qiwo_log_karts', :action => 'pagosPorOpenPay'
  match '/qiwo_log_karts/descargarPDF', :controller => 'qiwo_log_karts', :action => 'downloadPDF'
  match '/qiwo_log_karts/descargarXML', :controller => 'qiwo_log_karts', :action => 'downloadXML'
  resources :qiwo_log_karts

  resources :qiwo_log_searches 

  resources :qiwo_log_visits

  match '/h2h/direccionFacturacion', :controller => 'qiwo_enterprises', :action => 'getFiscalAddress'
  resources :qiwo_enterprises

  get '/tienda/:id', to: 'searches#show'
  resources :searches do 
      post :sendToInbox, on: :collection 
  end

  match '/qiwo_clients/cancelarFactura', :controller => 'qiwo_clients', :action => 'cancelFactura'
  match '/qiwo_clients/markAsCompleted', :controller => 'qiwo_clients', :action => 'markAsCompleted'
  match '/qiwo_clients/changeShippingPrice', :controller => 'qiwo_clients', :action => 'changeShippingPrice'
  match '/qiwo_clients/changeShippingGuide', :controller => 'qiwo_clients', :action => 'changeShippingGuide'
  match '/qiwo_clients/attachGuide', :controller => 'qiwo_clients', :action => 'attachGuide'
  resources :qiwo_clients do
    post :markAsCompleted, on: :collection 
  end
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '*path' => redirect('/')

end

app/models/qiwo_subscription.rb
class QiwoSubscription < ActiveRecord::Base
  attr_accessible :days_active, :id, :months_active, :places_allowed, :price, :products_allowed, :subscription_name, :description,:sale_point,:access_providers,:use_employees
end

app/controllers/qiwo_subscriptions_controller.rb
#!/bin/env ruby
# encoding: utf-8
class QiwoSubscriptionsController < ApplicationController
  # GET /qiwo_subscriptions
  # GET /qiwo_subscriptions.json
  def index

     if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_subscriptions = QiwoSubscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qiwo_subscriptions }
    end
  end

  # GET /qiwo_subscriptions/1
  # GET /qiwo_subscriptions/1.json
  def show
    if session[:activeUser].sys_rol!=1
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_subscription = QiwoSubscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qiwo_subscription }
    end
  end

  # GET /qiwo_subscriptions/new
  # GET /qiwo_subscriptions/new.json
  def new
    if session[:activeUser].sys_rol!=1
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_subscription = QiwoSubscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qiwo_subscription }
    end
  end

  # GET /qiwo_subscriptions/1/edit
  def edit
    if session[:activeUser].sys_rol==1
      @qiwo_subscription = QiwoSubscription.find(params[:id])
    end
      render layout: false 
  end

  # POST /qiwo_subscriptions
  # POST /qiwo_subscriptions.json
  def create
     if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    if session[:activeUser].sys_rol!=1
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_subscription = QiwoSubscription.new(params[:qiwo_subscription])
    #creamos una plantilla de plan en conekta

    respond_to do |format|
      if @qiwo_subscription.save
        Conekta.api_key=conektaKeyPrivate()
        plan = Conekta::Plan.create({
          :id => "qiwo-plan-"+@qiwo_subscription.id.to_s,
          :name => @qiwo_subscription.subscription_name,
          :amount => conektaFormat(@qiwo_subscription.price).to_s,
          :currency => "MXN",
          :interval => "month",
          :frequency => @qiwo_subscription.months_active.to_i,
          :trial_period_days => 0,
          :expiry_count => @qiwo_subscription.months_active.to_i})
        puts "CONEKTA PLAN>>>>:"+plan.inspect
        format.html { redirect_to "/qiwo_user_subscriptions", notice: 'Qiwo subscription was successfully created.' }
        format.json { render json: @qiwo_subscription, status: :created, location: @qiwo_subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @qiwo_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qiwo_subscriptions/1
  # PUT /qiwo_subscriptions/1.json
  def update
     if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    if session[:activeUser].sys_rol!=1
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_subscription = QiwoSubscription.find(params[:id])

    respond_to do |format|
      if @qiwo_subscription.update_attributes(params[:qiwo_subscription])
        format.html { redirect_to "/qiwo_user_subscriptions", notice: 'Suscripción actualizada.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qiwo_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qiwo_subscriptions/1
  # DELETE /qiwo_subscriptions/1.json
  def destroy
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    if session[:activeUser].sys_rol==1
      @qiwo_subscription = QiwoSubscription.find(params[:id])
      @qiwo_subscription.destroy

      respond_to do |format|
        format.html { redirect_to "/qiwo_user_subscriptions" }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/qiwo_subscriptions_helper.rb
module QiwoSubscriptionsHelper
end

app/views/qiwo_subscriptions/_form.html.erb
<%= simple_form_for @qiwo_subscription, :html => {:multipart => true,:class=>"form-horizontal form"} do |f| %>

  <%= f.error_notification %>

  
    <%= f.input :subscription_name,input_html: { class:'col-md-12 form-control' },label:"Nombre de suscripcion" %>
    <%= f.input :description,input_html: { class:'col-md-12 form-control',rows:"2"  },label:"Descripcion de suscripcion" %>
    <%= f.input :price,input_html: { class:'col-md-12 form-control' },label:"Precio (sin puntos)" %>
    <%= f.input :places_allowed,input_html: { class:'col-md-12 form-control' },label:"Negocios permitidos" %>
    <%= f.input :products_allowed,input_html: { class:'col-md-12 form-control' },label:"Productos permitidos" %>
    <%= f.input :days_active,input_html: { class:'col-md-12 form-control' },label:"Días activo" %>
    <%= f.input :months_active,input_html: { class:'col-md-12 form-control' },label:"Cada cuantos meses se renueva" %>
    <%= f.input :access_providers,as: :boolean,input_html: { class:'col-md-12 form-control' },label:"¿Tiene permisos para ver proveedores?" %>
    <%= f.input :use_employees,as: :boolean,input_html: { class:'col-md-12 form-control' },label:"¿Permiso para administrar empleados?" %>
    <%= f.input :sale_point,as: :boolean,input_html: { class:'col-md-12 form-control' },label:"¿Punto de venta activo?" %>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/qiwo_subscriptions/edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">                             
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">Modifica tu producto</h4>
        </div>
<div class="modal-body">
<%= render 'form' %>

 </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
    </div>

app/views/qiwo_subscriptions/index.html.erb
<h1>Listing qiwo_subscriptions</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Subscription name</th>
    <th>Price</th>
    <th>Places allowed</th>
    <th>Products allowed</th>
    <th>Days active</th>
    <th>Months active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qiwo_subscriptions.each do |qiwo_subscription| %>
  <tr>
    <td><%= qiwo_subscription.id %></td>
    <td><%= qiwo_subscription.subscription_name %></td>
    <td><%= qiwo_subscription.price %></td>
    <td><%= qiwo_subscription.places_allowed %></td>
    <td><%= qiwo_subscription.products_allowed %></td>
    <td><%= qiwo_subscription.days_active %></td>
    <td><%= qiwo_subscription.months_active %></td>
    <td><%= link_to 'Show', qiwo_subscription %></td>
    <td><%= link_to 'Edit', edit_qiwo_subscription_path(qiwo_subscription) %></td>
    <td><%= link_to 'Destroy', qiwo_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qiwo subscription', new_qiwo_subscription_path %>

app/views/qiwo_subscriptions/new.html.erb
<h1>New qiwo_subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', qiwo_subscriptions_path %>

app/views/qiwo_subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @qiwo_subscription.id %>
</p>

<p>
  <b>Subscription name:</b>
  <%= @qiwo_subscription.subscription_name %>
</p>

<p>
  <b>Price:</b>
  <%= @qiwo_subscription.price %>
</p>

<p>
  <b>Places allowed:</b>
  <%= @qiwo_subscription.places_allowed %>
</p>

<p>
  <b>Products allowed:</b>
  <%= @qiwo_subscription.products_allowed %>
</p>

<p>
  <b>Days active:</b>
  <%= @qiwo_subscription.days_active %>
</p>

<p>
  <b>Months active:</b>
  <%= @qiwo_subscription.months_active %>
</p>


<%= link_to 'Edit', edit_qiwo_subscription_path(@qiwo_subscription) %> |
<%= link_to 'Back', qiwo_subscriptions_path %>