config/routes.rb
Qiwo::Application.routes.draw do
  
  
  
  get '/articulo/:nombre', to: 'blogs#show'
  get '/portada/:frontpage', to: 'blogs#frontpage'
  resources :blogs

  resources :mailtemplates

  resources :qiwo_cfdis

  match '/redpacks/allowGuide', :controller => 'redpacks', :action => 'allowGuide'
  resources :redpacks

  resources :qiwo_profiles

  resources :shipping_guides

  resources :nfc_requests

  resources :cfdi_apis

  match '/facturacions/populateRollBack', :controller => 'facturacions', :action => 'populateRollBack'
  match '/facturacions/execRollBack', :controller => 'facturacions', :action => 'execRollBack'
  resources :facturacions

  match '/telegrams/validateTelegram', :controller => 'telegrams', :action => 'validateTelegram'
  match '/telegrams/login', :controller => 'telegrams', :action => 'emailLogin'
  match '/telegrams/ping', :controller => 'telegrams', :action => 'ping'
  match '/telegrams/telegram_actions', :controller => 'telegrams', :action => 'telegram_actions'
  resources :telegrams

  resources :nfc_readers

  resources :print_facturas

  resources :qiwo_counters

  resources :sat_documents

  match '/qiwo_employees/asociadoBuscar', :controller => 'qiwo_employees', :action => 'lookInFacebookEmployees'
  match '/qiwo_employees/misEmpleados', :controller => 'qiwo_employees', :action => 'listEmployees'
  match '/qiwo_employees/contratarEmpleado', :controller => 'qiwo_employees', :action => 'assignEmployee'
  match '/qiwo_employees/despedirEmpleado', :controller => 'qiwo_employees', :action => 'fireEmployee'
  resources :qiwo_employees

  resources :qiwo_orders

  match '/sale_points/puntoDeVentaProducto', :controller => 'sale_points', :action => 'searchByProduct'
  match '/sale_points/puntoDeVentaSKU', :controller => 'sale_points', :action => 'searchBySKU'
  match '/sale_points/puntoDeVentaNuevaOrden', :controller => 'sale_points', :action => 'createNewOrder'
  match '/sale_points/puntoDeVentaItems', :controller => 'sale_points', :action => 'getOrderItems'
  match '/sale_points/puntoDeVentaAlterItems', :controller => 'sale_points', :action => 'addProductToOrder'
  match '/sale_points/puntoDeVentaAlterGetTax', :controller => 'sale_points', :action => 'getTaxAddons'
  match '/sale_points/puntoDeVentaAlterSetTax', :controller => 'sale_points', :action => 'setTaxAddons'
  match '/sale_points/puntoDeVentaCloseOrder', :controller => 'sale_points', :action => 'closeOrder'
  match '/sale_points/puntoDeVentaValidar', :controller => 'sale_points', :action => 'validateOrderPayment'
  match '/sale_points/puntoDeVentaCerrarCuenta', :controller => 'sale_points', :action => 'closeWithNoInvoice'
  match '/sale_points/fd_card', :controller => 'sale_points', :action => 'first_data_card'
  resources :sale_points

  resources :cartera_clientes

  resources :payments

  resources :qiwo_subscriptions

  match '/qiwo_user_subscriptions/paySubscription', :controller => 'qiwo_user_subscriptions', :action => 'paySubscription'
  match '/qiwo_user_subscriptions/incomingFromPaypal', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromPaypal'
  match '/gateway/incomingFromConekta', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromConekta'
  match '/gateway/incomingFromOpenPay', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromOpenPay'
  resources :qiwo_user_subscriptions

  match '/qiwo_tools/updateMerchantTools', :controller => 'qiwo_tools', :action => 'updateMerchantTools'
  resources :qiwo_tools

  

  resources :qiwo_measure_units

  match '/yo/sendMessageToAll', :controller => 'yo', :action => 'sendMessageToAll'
  match '/yo/getCalendar', :controller => 'yo', :action => 'getCalendar'
  match '/yo/qiwoLogOut', :controller => 'yo', :action => 'qiwoLogOut'
  match '/yo/createGuides', :controller => 'yo', :action => 'createGuides'
  match '/yo/reassignPlan', :controller => 'yo', :action => 'reassignPlan'
  match '/yo/reassignCFDI', :controller => 'yo', :action => 'reassignCFDI'
  match '/yo/qtinbo', :controller => 'yo', :action => 'qtinbo'
  get '/yo', to: redirect('/dashboard')
  get 'dashboard', to: 'yo#index'

  resources :qiwo_categories

  match '/suscribir/me', :controller => 'welcome', :action => 'suscribir'
  root :to => 'welcome#index'

  resources :qiwo_item_tags

  resources :qiwo_tags

  resources :qiwo_product_categories

  resources :qiwo_coupons

  resources :qiwo_ranks

  resources :qiwo_reviews

  match '/qiwo_products/applyDiscount', :controller => 'qiwo_products', :action => 'applyDiscount'
  match '/qiwo_products/compartir', :controller => 'qiwo_products', :action => 'shareProduct'
  match '/qiwo_products/getProductsAsToken', :controller => 'qiwo_products', :action => 'getProductsAsToken'
  resources :qiwo_products

  resources :qiwo_images

  match '/qiwo_log_karts/oxxoPayment', :controller => 'qiwo_log_karts', :action => 'oxxoPayment'
  match '/qiwo_log_karts/banortePayment', :controller => 'qiwo_log_karts', :action => 'banortePayment'
  match '/qiwo_log_karts/thirdPartySale', :controller => 'qiwo_log_karts', :action => 'thirdPartySale'
  match '/qiwo_log_karts/basicPayments', :controller => 'qiwo_log_karts', :action => 'pagosPorOpenPay'
  match '/qiwo_log_karts/descargarPDF', :controller => 'qiwo_log_karts', :action => 'downloadPDF'
  match '/qiwo_log_karts/descargarXML', :controller => 'qiwo_log_karts', :action => 'downloadXML'
  resources :qiwo_log_karts

  resources :qiwo_log_searches 

  resources :qiwo_log_visits

  match '/h2h/direccionFacturacion', :controller => 'qiwo_enterprises', :action => 'getFiscalAddress'
  resources :qiwo_enterprises

  get '/tienda/:id', to: 'searches#show'
  resources :searches do 
      post :sendToInbox, on: :collection 
  end

  match '/qiwo_clients/cancelarFactura', :controller => 'qiwo_clients', :action => 'cancelFactura'
  match '/qiwo_clients/markAsCompleted', :controller => 'qiwo_clients', :action => 'markAsCompleted'
  match '/qiwo_clients/changeShippingPrice', :controller => 'qiwo_clients', :action => 'changeShippingPrice'
  match '/qiwo_clients/changeShippingGuide', :controller => 'qiwo_clients', :action => 'changeShippingGuide'
  match '/qiwo_clients/attachGuide', :controller => 'qiwo_clients', :action => 'attachGuide'
  resources :qiwo_clients do
    post :markAsCompleted, on: :collection 
  end
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '*path' => redirect('/')

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :seed
end

app/controllers/searches_controller.rb
#!/bin/env ruby
# encoding: utf-8
require '/usr/src/qiwo/app/models/qiwo_product.rb'
require '/usr/src/qiwo/app/models/qiwo_log_kart.rb'
require '/usr/src/qiwo/app/models/qiwo_review.rb'
require '/usr/src/qiwo/app/models/qiwo_enterprise.rb'
require '/usr/src/qiwo/app/models/sys_user.rb'
require '/usr/src/qiwo/app/models/qiwo_log_visit.rb'
require '/usr/src/qiwo/app/models/qiwo_log_search.rb'
require '/usr/src/qiwo/app/models/qiwo_category.rb'
require '/usr/src/qiwo/app/models/qiwo_image.rb'
require '/usr/src/qiwo/app/controllers/notifications.rb'
require 'open-uri'
require 'json'
require 'xmpp4r_facebook'
require 'xmpp4r/roster'
require 'fb_graph'
require 'timeout'
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    redirect_to "/"
    return
    @searches = Search.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1.
  # GET /searches/1.json
  def show
    qiwoUser=session[:activeUser]
    begin
    status = Timeout::timeout(3) {
    regionService = JSON.parse(open("http://freegeoip.net/json/"+request.remote_ip.to_s).read)
    if qiwoUser!=nil
      #if the user is not empty save the data
      @qiwoSearch=QiwoLogSearch.new(:ip_user=>request.remote_ip.to_s,:facebook_id=>qiwoUser.user_id,:user_id=>qiwoUser.id,:search_term=>params[:id],:country=>regionService["country_name"],:city=>regionService["region_name"]+","+regionService["city"])
      @qiwoSearch.save
    else
        #modificar la semilla
        
        @qiwoSearch=QiwoLogSearch.new(:ip_user=>request.remote_ip.to_s,:search_term=>params[:id],:country=>regionService["country_name"],:city=>regionService["region_name"]+","+regionService["city"])
      @qiwoSearch.save
      
   
    end
  }
   rescue Exception => e
      
    end
    @productSearch=globalQiwoSearch(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @productSearch }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    redirect_to "/"
    return
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
      @search=QiwoProduct.find_by_id(params[:id])
      render layout: false
  end

  # POST /searches
  # POST /searches.json
  def create
    redirect_to "/"
    return
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    redirect_to "/"
    return
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    redirect_to "/"
    return
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
    
    
  def sendToInbox
      puts params.inspect
      puts "sendToInbox was executed"
      qiwoUser=session[:activeUser]
      if qiwoUser!=nil
        Notifications.sendInfoToInbox(session,params[:prodid])
          puts "enviando mensaje"
      end
      render :nothing => true, :status => 200
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= simple_form_for @search, :html => {:multipart => true,:class=>"form-horizontal portlet-body form"} do |f| %>
  
<div class="row">
<div class="col-md-6">

    <%= f.input :name, required:true,label:"Nombre",input_html: { class:'col-md-12 form-control' } %>

    <%= f.input :business_source, required:true,label:"Negocio",:collection => QiwoEnterprise.where(:user_owner=>session[:activeUser]),:label_method => :name, :value_method => :id,input_html: { class:'col-md-12 form-control' } %>

    <%= f.input :sale_price,label:"Precio venta",required:true,input_html: { class:'col-md-12 form-control' } %>

    <%= f.input :major_quantity,required:true,label:"Mayoreo a partir de",input_html: { class:'col-md-12 form-control' } %>

    <%= f.input :major_price,label:"Precio myoreo",required:true,input_html: { class:'col-md-12 form-control' } %>

    <%= f.input :stock_items,required:true,label:"Unidades en stock",input_html: { class:'col-md-12 form-control' } %>
    </div>
<div class="col-md-6">

    <%= f.input :description,:as=>:text,required:true,label:"Descripcion",input_html: { class:'col-md-12 form-control',rows:"3" } %>
    <%= f.input :keywords,required:true,label:"Palabras clave",input_html: { class:'form-control tags medium',placeholder:"Escriba una palabra y presione enter",id:'tags_2',rows:"3" } %>
    <div class="modal-footer">
        
            <button type="button" class="btn default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn blue">Enviar a mi telefono<i class="icon-facebook-sign"></i> </button>
        </div>
    
    </div>

    

  
<% end %>
</div>

app/views/searches/edit.html.erb
<img src='http://s3.amazonaws.com/ultimate_whip/garage_photos/photos/000/000/079/large/38779594009_original.jpeg?1349826286'>

<div class="description">
  <h1>Title of Modal</h1>
  <p>Put whatever content you need here. I personally used it for comments and tags :)</p>
</div>

app/views/searches/edit_backup.html.erb
<div class="modal-dialog">
    <div class="modal-content">                             
        
            <div class="modal-body">
                <div class="thumbnail">
                <div style="position: relative; ">

                <% if @search.discount_amount>0 %>
                <div class="wrapper">
                    <div class="ribbon-wrapper-green">
                          <div class="ribbon-green">¡Este producto tiene descuento!
                          <br />¡<%= number_with_precision((@search.discount_amount*100)/@search.sale_price.to_i,precision:2) %>%!
                          </div>
                      </div>
                </div>
                <% end %>
                          <% if @search.image_id_file_name==nil or @search.image_id_file_name=="" %>
                              <img src="/assets/img/label_tag.png" alt="" style="width: 100%; ">
                              <% else %>

                              
                                <div class="theme-default">
                                <div id="slider" class="nivoSlider"> 
                                    
                                    
                                      <img src="/system/qiwo_products/image_ids/000/000/<% if @search.id<10 %><%= '00' %><% elsif @search.id<100 %><%= '0' %><% end %><%= @search.id %>/medium/<%= @search.image_id_file_name %>" alt="" style="width: 100%; ">
                                      <% if @search.image_one_file_name!=nil %>
                                        <img src="<%= @search.image_one.url %>" alt="" style="width: 100%; ">
                                      <% end %>
                                      <% if @search.image_two_file_name!=nil %>
                                        <img src="<%= @search.image_two.url %>" alt="" style="width: 100%; ">
                                      <% end %>
                                      <% if @search.image_three_file_name!=nil %>
                                        <img src="<%= @search.image_three.url %>" alt="" style="width: 100%; ">
                                      <% end %>
                                    
                              </div>
                              <div id="htmlcaption" class="nivo-html-caption">
                                  
                              </div>
                          </div>


                             
                                
                              





                              <% end %>
                              <div id="example" style="position: absolute;top: 0px;left: 0px;padding: 0px;"><h3><span class="label label-warning">Un producto de <%= QiwoEnterprise.find_by_id(@search.business_source).name %></span></h3></div>
                              </div>
                              <div class="caption">
                                 
                                 <p><a href="javascript:sendit(<%= @search.id %>);" class="btn blue">Enviar a mi telefono <i class="icon-facebook"></i></a>
                                 <% if QiwoEnterprise.find_by_id(@search.business_source).location!=nil %>
                                  <a href="http://maps.google.com/?q=<%= QiwoEnterprise.find_by_id(@search.business_source).location.split("\n").join(",") %>" target="_blank" class="btn green">Abrir en mapa<i class="icon-map-marker"></i></a>
                                  <% end %>
                                  </p>

                                  <h3>$<%= number_with_precision(@search.sale_price+(@search.tax==1? getTax(@search.sale_price) : 0),precision:2) %> MXN <%= @search.name %> </h3>
                                 <p><%= @search.description %></p>
                                  <br>
                                   <p> <i class="icon-map-marker"></i><%= QiwoEnterprise.find_by_id(@search.business_source).location %></p>
                                   <br>

                                  
                                 <div class="form-group">
                              
                              <div class="col-md-9">
                                 <div id="spinner3">
                                    <div class="input-group" style="width:150px;">
                                       <input type="text" class="spinner-input form-control" maxlength="3" readonly>
                                       <div class="spinner-buttons input-group-btn">                   
                                          <button type="button" class="btn spinner-up default">                       
                                          <i class="icon-angle-up"></i>                    
                                          </button>                     
                                          <button type="button" class="btn spinner-down default">                        
                                          <i class="icon-angle-down"></i>                     
                                          </button>                  
                                       </div>
                                    </div>
                                 </div>
                                 <span class="help-block">
                                 Con un máximo de: <%= @search.stock_items %>
                                 </span>
                              </div>
                              <a href="javascript:addToMyKart();" class="btn green">Agregar al carrito<i class="icon-shopping-cart"></i></a>
                              
                           </div>

                                  <br>
                                 <div class="caption"><i class="icon-comments"></i>Comentarios</div>
                                  <% comentariosProduct=QiwoReview.find_all_by_product_id(@search.id) %>
                                  <% if comentariosProduct.length>3 %>
                            <div  style="height: 435px;overflow: auto;" >
                         <% else %>
                            <div  style="height: 100px;overflow: auto;" >
                         <% end %>
                        <ul class="chats" id="comments-prod-<%= @search.id %>">
                            <% isInorOut="in" %>
                            <% comentariosProduct.each do |singlecomment| %>
                            <% userInComment=Sys_User.find_by_id(singlecomment.user_id) %>
                            
                           <li class="<%= isInorOut %>">
                               <% if isInorOut=="in" %>
                               <% isInorOut="out" %>
                               <% else %>
                               <% isInorOut="in" %>
                               <% end %>
                              <img class="avatar img-responsive" alt="" src="<%= userInComment.avatar %>" />
                              <div class="message">
                                 <span class="arrow"></span>
                                 <a href="#" class="name"><%= userInComment.name %><%= userInComment.last_name %></a>
                                 <span class="datetime"> at <%= singlecomment.created_at %></span>
                                 <span class="body">
                                 <%= singlecomment.review %>
                                 </span>
                              </div>
                           </li>
                           <% end %>
                        </ul>
                     </div>
                    <% if session[:activeUser]!=nil %>
                    
                     <div class="chat-form">
                        <div class="input-cont">   
                           <input class="form-control" type="text" placeholder="Escribe un comentario..." id="new-comment-<%= @search.id %>"/>
                        </div>
                        <div class="btn-cont"> 
                           <span class="arrow"></span>
                           <a href="javascript:submitComment('<%= @search.id %>',<%= @search.id %>,'xor');" class="btn blue icn-only"><i class="icon-ok icon-white"></i></a>
                        </div>
                     </div>
                    <% else %>
                        <div class="chat-form">
                        <div class="input-cont">   
                           <input class="form-control disabled" type="text" placeholder="Inicia sesión para comentar" disabled  />
                        </div>
                        <div class="btn-cont"> 
                           <span class="arrow"></span>
                           <a href="" class="btn blue icn-only disabled"><i class="icon-ok icon-white"></i></a>
                        </div>
                     </div>       
                    <% end %>
               

                                 
                                  <a href="#" class="btn red" data-dismiss="modal" aria-hidden="true">Cerrar</a>
                              </div>
                              <div>Aceptamos 
                        <img src="http://finance.avafin.com/images/paypal-icon.gif" alt="">
                        <img src="/assets/img/visa_logo.png" alt="">
                        <img src="/assets/img/oxxo_logo.png" alt="">
                        <img src="/assets/img/mastercard_logo.png" alt="">
                        <img src="/assets/img/banorte_logo.png" alt=""></div>
                              
                           </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<script type="text/javascript"> 
function addToMyKart(){
  addToKart(<%= @search.id %>,$('#spinner3').spinner('value'));
}


      startImgSlider();

FormComponents.init();
</script>

app/views/searches/index.html.erb
<%= render "shared/topmenu" %>

<section class="hbox stretch">
    <!-- .aside -->
    
    <!-- /.aside -->
    <!-- .vbox -->
    <section id="content">
      <section class="vbox">
        <header class="header">
          <p>Galería</p>
        </header>
        <section class="scrollable">
          <div class="text-center m-t-lg clearfix wrapper-lg animated fadeInRightBig" id="galleryLoading">
            <h1 class="white">Coinless Resultados <i class="icon-cloud"></i></h1>
            <h3 class="text-muted">Resultados</h3>
            <p class="m-t-lg"><i class="icon-spinner icon-spin icon-2x"></i></p>
          </div>
          <div id="gallery" class="gallery hide">
            
          </div>
        </section>
      </section>
      <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
    </section>
    <!-- /.vbox -->
  </section>

app/views/searches/index_bak.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Seed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.seed %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show_bak.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seed:</b>
  <%= @search.seed %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>