config/routes.rb
Qiwo::Application.routes.draw do
  
  
  
  get '/articulo/:nombre', to: 'blogs#show'
  get '/portada/:frontpage', to: 'blogs#frontpage'
  resources :blogs

  resources :mailtemplates

  resources :qiwo_cfdis

  match '/redpacks/allowGuide', :controller => 'redpacks', :action => 'allowGuide'
  resources :redpacks

  resources :qiwo_profiles

  resources :shipping_guides

  resources :nfc_requests

  resources :cfdi_apis

  match '/facturacions/populateRollBack', :controller => 'facturacions', :action => 'populateRollBack'
  match '/facturacions/execRollBack', :controller => 'facturacions', :action => 'execRollBack'
  resources :facturacions

  match '/telegrams/validateTelegram', :controller => 'telegrams', :action => 'validateTelegram'
  match '/telegrams/login', :controller => 'telegrams', :action => 'emailLogin'
  match '/telegrams/ping', :controller => 'telegrams', :action => 'ping'
  match '/telegrams/telegram_actions', :controller => 'telegrams', :action => 'telegram_actions'
  resources :telegrams

  resources :nfc_readers

  resources :print_facturas

  resources :qiwo_counters

  resources :sat_documents

  match '/qiwo_employees/asociadoBuscar', :controller => 'qiwo_employees', :action => 'lookInFacebookEmployees'
  match '/qiwo_employees/misEmpleados', :controller => 'qiwo_employees', :action => 'listEmployees'
  match '/qiwo_employees/contratarEmpleado', :controller => 'qiwo_employees', :action => 'assignEmployee'
  match '/qiwo_employees/despedirEmpleado', :controller => 'qiwo_employees', :action => 'fireEmployee'
  resources :qiwo_employees

  resources :qiwo_orders

  match '/sale_points/puntoDeVentaProducto', :controller => 'sale_points', :action => 'searchByProduct'
  match '/sale_points/puntoDeVentaSKU', :controller => 'sale_points', :action => 'searchBySKU'
  match '/sale_points/puntoDeVentaNuevaOrden', :controller => 'sale_points', :action => 'createNewOrder'
  match '/sale_points/puntoDeVentaItems', :controller => 'sale_points', :action => 'getOrderItems'
  match '/sale_points/puntoDeVentaAlterItems', :controller => 'sale_points', :action => 'addProductToOrder'
  match '/sale_points/puntoDeVentaAlterGetTax', :controller => 'sale_points', :action => 'getTaxAddons'
  match '/sale_points/puntoDeVentaAlterSetTax', :controller => 'sale_points', :action => 'setTaxAddons'
  match '/sale_points/puntoDeVentaCloseOrder', :controller => 'sale_points', :action => 'closeOrder'
  match '/sale_points/puntoDeVentaValidar', :controller => 'sale_points', :action => 'validateOrderPayment'
  match '/sale_points/puntoDeVentaCerrarCuenta', :controller => 'sale_points', :action => 'closeWithNoInvoice'
  match '/sale_points/fd_card', :controller => 'sale_points', :action => 'first_data_card'
  resources :sale_points

  resources :cartera_clientes

  resources :payments

  resources :qiwo_subscriptions

  match '/qiwo_user_subscriptions/paySubscription', :controller => 'qiwo_user_subscriptions', :action => 'paySubscription'
  match '/qiwo_user_subscriptions/incomingFromPaypal', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromPaypal'
  match '/gateway/incomingFromConekta', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromConekta'
  match '/gateway/incomingFromOpenPay', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromOpenPay'
  resources :qiwo_user_subscriptions

  match '/qiwo_tools/updateMerchantTools', :controller => 'qiwo_tools', :action => 'updateMerchantTools'
  resources :qiwo_tools

  

  resources :qiwo_measure_units

  match '/yo/sendMessageToAll', :controller => 'yo', :action => 'sendMessageToAll'
  match '/yo/getCalendar', :controller => 'yo', :action => 'getCalendar'
  match '/yo/qiwoLogOut', :controller => 'yo', :action => 'qiwoLogOut'
  match '/yo/createGuides', :controller => 'yo', :action => 'createGuides'
  match '/yo/reassignPlan', :controller => 'yo', :action => 'reassignPlan'
  match '/yo/reassignCFDI', :controller => 'yo', :action => 'reassignCFDI'
  match '/yo/qtinbo', :controller => 'yo', :action => 'qtinbo'
  get '/yo', to: redirect('/dashboard')
  get 'dashboard', to: 'yo#index'

  resources :qiwo_categories

  match '/suscribir/me', :controller => 'welcome', :action => 'suscribir'
  root :to => 'welcome#index'

  resources :qiwo_item_tags

  resources :qiwo_tags

  resources :qiwo_product_categories

  resources :qiwo_coupons

  resources :qiwo_ranks

  resources :qiwo_reviews

  match '/qiwo_products/applyDiscount', :controller => 'qiwo_products', :action => 'applyDiscount'
  match '/qiwo_products/compartir', :controller => 'qiwo_products', :action => 'shareProduct'
  match '/qiwo_products/getProductsAsToken', :controller => 'qiwo_products', :action => 'getProductsAsToken'
  resources :qiwo_products

  resources :qiwo_images

  match '/qiwo_log_karts/oxxoPayment', :controller => 'qiwo_log_karts', :action => 'oxxoPayment'
  match '/qiwo_log_karts/banortePayment', :controller => 'qiwo_log_karts', :action => 'banortePayment'
  match '/qiwo_log_karts/thirdPartySale', :controller => 'qiwo_log_karts', :action => 'thirdPartySale'
  match '/qiwo_log_karts/basicPayments', :controller => 'qiwo_log_karts', :action => 'pagosPorOpenPay'
  match '/qiwo_log_karts/descargarPDF', :controller => 'qiwo_log_karts', :action => 'downloadPDF'
  match '/qiwo_log_karts/descargarXML', :controller => 'qiwo_log_karts', :action => 'downloadXML'
  resources :qiwo_log_karts

  resources :qiwo_log_searches 

  resources :qiwo_log_visits

  match '/h2h/direccionFacturacion', :controller => 'qiwo_enterprises', :action => 'getFiscalAddress'
  resources :qiwo_enterprises

  get '/tienda/:id', to: 'searches#show'
  resources :searches do 
      post :sendToInbox, on: :collection 
  end

  match '/qiwo_clients/cancelarFactura', :controller => 'qiwo_clients', :action => 'cancelFactura'
  match '/qiwo_clients/markAsCompleted', :controller => 'qiwo_clients', :action => 'markAsCompleted'
  match '/qiwo_clients/changeShippingPrice', :controller => 'qiwo_clients', :action => 'changeShippingPrice'
  match '/qiwo_clients/changeShippingGuide', :controller => 'qiwo_clients', :action => 'changeShippingGuide'
  match '/qiwo_clients/attachGuide', :controller => 'qiwo_clients', :action => 'attachGuide'
  resources :qiwo_clients do
    post :markAsCompleted, on: :collection 
  end
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '*path' => redirect('/')

end

app/models/cartera_cliente.rb
class CarteraCliente < ActiveRecord::Base
  attr_accessible :contacto_email, :contacto_name, :is_client, :location_lat, :location_lon, :negocio, :next_visit, :observaciones, :telefono, :visitado
end

app/controllers/cartera_clientes_controller.rb
#!/bin/env ruby
# encoding: utf-8
class CarteraClientesController < ApplicationController
  # GET /cartera_clientes
  # GET /cartera_clientes.json
  def index
    @cartera_clientes = CarteraCliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cartera_clientes }
    end
  end

  # GET /cartera_clientes/1
  # GET /cartera_clientes/1.json
  def show
    @cartera_cliente = CarteraCliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cartera_cliente }
    end
  end

  # GET /cartera_clientes/new
  # GET /cartera_clientes/new.json
  def new
    @cartera_cliente = CarteraCliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cartera_cliente }
    end
  end

  # GET /cartera_clientes/1/edit
  def edit
    @cartera_cliente = CarteraCliente.find(params[:id])
  end

  # POST /cartera_clientes
  # POST /cartera_clientes.json
  def create
    @cartera_cliente = CarteraCliente.new(params[:cartera_cliente])

    respond_to do |format|
      if @cartera_cliente.save
        format.html { redirect_to @cartera_cliente, notice: 'Cartera cliente was successfully created.' }
        format.json { render json: @cartera_cliente, status: :created, location: @cartera_cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cartera_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cartera_clientes/1
  # PUT /cartera_clientes/1.json
  def update
    @cartera_cliente = CarteraCliente.find(params[:id])

    respond_to do |format|
      if @cartera_cliente.update_attributes(params[:cartera_cliente])
        format.html { redirect_to @cartera_cliente, notice: 'Cartera cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cartera_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartera_clientes/1
  # DELETE /cartera_clientes/1.json
  def destroy
    @cartera_cliente = CarteraCliente.find(params[:id])
    @cartera_cliente.destroy

    respond_to do |format|
      format.html { redirect_to cartera_clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cartera_clientes_helper.rb
module CarteraClientesHelper
end

app/views/cartera_clientes/_form.html.erb
<%= simple_form_for(@cartera_cliente) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :negocio %>
    <%= f.input :contacto_email %>
    <%= f.input :contacto_name %>
    <%= f.input :telefono %>
    <%= f.input :location_lat %>
    <%= f.input :location_lon %>
    <%= f.input :observaciones %>
    <%= f.input :visitado %>
    <%= f.input :is_client %>
    <%= f.input :next_visit %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cartera_clientes/edit.html.erb
<h1>Editing cartera_cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cartera_cliente %> |
<%= link_to 'Back', cartera_clientes_path %>

app/views/cartera_clientes/index.html.erb
<h1>Listing cartera_clientes</h1>

<table>
  <tr>
    <th>Negocio</th>
    <th>Contacto email</th>
    <th>Contacto name</th>
    <th>Telefono</th>
    <th>Location lat</th>
    <th>Location lon</th>
    <th>Observaciones</th>
    <th>Visitado</th>
    <th>Is client</th>
    <th>Next visit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cartera_clientes.each do |cartera_cliente| %>
  <tr>
    <td><%= cartera_cliente.negocio %></td>
    <td><%= cartera_cliente.contacto_email %></td>
    <td><%= cartera_cliente.contacto_name %></td>
    <td><%= cartera_cliente.telefono %></td>
    <td><%= cartera_cliente.location_lat %></td>
    <td><%= cartera_cliente.location_lon %></td>
    <td><%= cartera_cliente.observaciones %></td>
    <td><%= cartera_cliente.visitado %></td>
    <td><%= cartera_cliente.is_client %></td>
    <td><%= cartera_cliente.next_visit %></td>
    <td><%= link_to 'Show', cartera_cliente %></td>
    <td><%= link_to 'Edit', edit_cartera_cliente_path(cartera_cliente) %></td>
    <td><%= link_to 'Destroy', cartera_cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cartera cliente', new_cartera_cliente_path %>

app/views/cartera_clientes/new.html.erb
<h1>New cartera_cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', cartera_clientes_path %>

app/views/cartera_clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Negocio:</b>
  <%= @cartera_cliente.negocio %>
</p>

<p>
  <b>Contacto email:</b>
  <%= @cartera_cliente.contacto_email %>
</p>

<p>
  <b>Contacto name:</b>
  <%= @cartera_cliente.contacto_name %>
</p>

<p>
  <b>Telefono:</b>
  <%= @cartera_cliente.telefono %>
</p>

<p>
  <b>Location lat:</b>
  <%= @cartera_cliente.location_lat %>
</p>

<p>
  <b>Location lon:</b>
  <%= @cartera_cliente.location_lon %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @cartera_cliente.observaciones %>
</p>

<p>
  <b>Visitado:</b>
  <%= @cartera_cliente.visitado %>
</p>

<p>
  <b>Is client:</b>
  <%= @cartera_cliente.is_client %>
</p>

<p>
  <b>Next visit:</b>
  <%= @cartera_cliente.next_visit %>
</p>


<%= link_to 'Edit', edit_cartera_cliente_path(@cartera_cliente) %> |
<%= link_to 'Back', cartera_clientes_path %>