config/routes.rb
Qiwo::Application.routes.draw do
  
  
  
  get '/articulo/:nombre', to: 'blogs#show'
  get '/portada/:frontpage', to: 'blogs#frontpage'
  resources :blogs

  resources :mailtemplates

  resources :qiwo_cfdis

  match '/redpacks/allowGuide', :controller => 'redpacks', :action => 'allowGuide'
  resources :redpacks

  resources :qiwo_profiles

  resources :shipping_guides

  resources :nfc_requests

  resources :cfdi_apis

  match '/facturacions/populateRollBack', :controller => 'facturacions', :action => 'populateRollBack'
  match '/facturacions/execRollBack', :controller => 'facturacions', :action => 'execRollBack'
  resources :facturacions

  match '/telegrams/validateTelegram', :controller => 'telegrams', :action => 'validateTelegram'
  match '/telegrams/login', :controller => 'telegrams', :action => 'emailLogin'
  match '/telegrams/ping', :controller => 'telegrams', :action => 'ping'
  match '/telegrams/telegram_actions', :controller => 'telegrams', :action => 'telegram_actions'
  resources :telegrams

  resources :nfc_readers

  resources :print_facturas

  resources :qiwo_counters

  resources :sat_documents

  match '/qiwo_employees/asociadoBuscar', :controller => 'qiwo_employees', :action => 'lookInFacebookEmployees'
  match '/qiwo_employees/misEmpleados', :controller => 'qiwo_employees', :action => 'listEmployees'
  match '/qiwo_employees/contratarEmpleado', :controller => 'qiwo_employees', :action => 'assignEmployee'
  match '/qiwo_employees/despedirEmpleado', :controller => 'qiwo_employees', :action => 'fireEmployee'
  resources :qiwo_employees

  resources :qiwo_orders

  match '/sale_points/puntoDeVentaProducto', :controller => 'sale_points', :action => 'searchByProduct'
  match '/sale_points/puntoDeVentaSKU', :controller => 'sale_points', :action => 'searchBySKU'
  match '/sale_points/puntoDeVentaNuevaOrden', :controller => 'sale_points', :action => 'createNewOrder'
  match '/sale_points/puntoDeVentaItems', :controller => 'sale_points', :action => 'getOrderItems'
  match '/sale_points/puntoDeVentaAlterItems', :controller => 'sale_points', :action => 'addProductToOrder'
  match '/sale_points/puntoDeVentaAlterGetTax', :controller => 'sale_points', :action => 'getTaxAddons'
  match '/sale_points/puntoDeVentaAlterSetTax', :controller => 'sale_points', :action => 'setTaxAddons'
  match '/sale_points/puntoDeVentaCloseOrder', :controller => 'sale_points', :action => 'closeOrder'
  match '/sale_points/puntoDeVentaValidar', :controller => 'sale_points', :action => 'validateOrderPayment'
  match '/sale_points/puntoDeVentaCerrarCuenta', :controller => 'sale_points', :action => 'closeWithNoInvoice'
  match '/sale_points/fd_card', :controller => 'sale_points', :action => 'first_data_card'
  resources :sale_points

  resources :cartera_clientes

  resources :payments

  resources :qiwo_subscriptions

  match '/qiwo_user_subscriptions/paySubscription', :controller => 'qiwo_user_subscriptions', :action => 'paySubscription'
  match '/qiwo_user_subscriptions/incomingFromPaypal', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromPaypal'
  match '/gateway/incomingFromConekta', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromConekta'
  match '/gateway/incomingFromOpenPay', :controller => 'qiwo_user_subscriptions', :action => 'incomingFromOpenPay'
  resources :qiwo_user_subscriptions

  match '/qiwo_tools/updateMerchantTools', :controller => 'qiwo_tools', :action => 'updateMerchantTools'
  resources :qiwo_tools

  

  resources :qiwo_measure_units

  match '/yo/sendMessageToAll', :controller => 'yo', :action => 'sendMessageToAll'
  match '/yo/getCalendar', :controller => 'yo', :action => 'getCalendar'
  match '/yo/qiwoLogOut', :controller => 'yo', :action => 'qiwoLogOut'
  match '/yo/createGuides', :controller => 'yo', :action => 'createGuides'
  match '/yo/reassignPlan', :controller => 'yo', :action => 'reassignPlan'
  match '/yo/reassignCFDI', :controller => 'yo', :action => 'reassignCFDI'
  match '/yo/qtinbo', :controller => 'yo', :action => 'qtinbo'
  get '/yo', to: redirect('/dashboard')
  get 'dashboard', to: 'yo#index'

  resources :qiwo_categories

  match '/suscribir/me', :controller => 'welcome', :action => 'suscribir'
  root :to => 'welcome#index'

  resources :qiwo_item_tags

  resources :qiwo_tags

  resources :qiwo_product_categories

  resources :qiwo_coupons

  resources :qiwo_ranks

  resources :qiwo_reviews

  match '/qiwo_products/applyDiscount', :controller => 'qiwo_products', :action => 'applyDiscount'
  match '/qiwo_products/compartir', :controller => 'qiwo_products', :action => 'shareProduct'
  match '/qiwo_products/getProductsAsToken', :controller => 'qiwo_products', :action => 'getProductsAsToken'
  resources :qiwo_products

  resources :qiwo_images

  match '/qiwo_log_karts/oxxoPayment', :controller => 'qiwo_log_karts', :action => 'oxxoPayment'
  match '/qiwo_log_karts/banortePayment', :controller => 'qiwo_log_karts', :action => 'banortePayment'
  match '/qiwo_log_karts/thirdPartySale', :controller => 'qiwo_log_karts', :action => 'thirdPartySale'
  match '/qiwo_log_karts/basicPayments', :controller => 'qiwo_log_karts', :action => 'pagosPorOpenPay'
  match '/qiwo_log_karts/descargarPDF', :controller => 'qiwo_log_karts', :action => 'downloadPDF'
  match '/qiwo_log_karts/descargarXML', :controller => 'qiwo_log_karts', :action => 'downloadXML'
  resources :qiwo_log_karts

  resources :qiwo_log_searches 

  resources :qiwo_log_visits

  match '/h2h/direccionFacturacion', :controller => 'qiwo_enterprises', :action => 'getFiscalAddress'
  resources :qiwo_enterprises

  get '/tienda/:id', to: 'searches#show'
  resources :searches do 
      post :sendToInbox, on: :collection 
  end

  match '/qiwo_clients/cancelarFactura', :controller => 'qiwo_clients', :action => 'cancelFactura'
  match '/qiwo_clients/markAsCompleted', :controller => 'qiwo_clients', :action => 'markAsCompleted'
  match '/qiwo_clients/changeShippingPrice', :controller => 'qiwo_clients', :action => 'changeShippingPrice'
  match '/qiwo_clients/changeShippingGuide', :controller => 'qiwo_clients', :action => 'changeShippingGuide'
  match '/qiwo_clients/attachGuide', :controller => 'qiwo_clients', :action => 'attachGuide'
  resources :qiwo_clients do
    post :markAsCompleted, on: :collection 
  end
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '*path' => redirect('/')

end

app/models/qiwo_category.rb
class QiwoCategory < ActiveRecord::Base
  attr_accessible :category_name, :id, :parent_category
end

app/controllers/qiwo_categories_controller.rb
#!/bin/env ruby
# encoding: utf-8
class QiwoCategoriesController < ApplicationController
  # GET /qiwo_categories
  # GET /qiwo_categories.json
  def index
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    #primero traer los insumos
    insumos=QiwoTag.where(:id=>session[:activeUser].id).last
    #ahora recorrer los insumos y usar la busqueda
    @qiwo_categories = QiwoCategory.all
    if insumos!=nil
      if insumos.tag_name!=nil and insumos.tag_name!=""
        @qiwo_providers=globalQiwoSearch(insumos.tag_name.split(",").join(" "))      
      else
        @qiwo_providers=[]
      end
    else
      @qiwo_providers=[]
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qiwo_categories }
    end
  end

  # GET /qiwo_categories/1
  # GET /qiwo_categories/1.json
  def show
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qiwo_category }
    end
  end

  # GET /qiwo_categories/new
  # GET /qiwo_categories/new.json
  def new
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qiwo_category }
    end
  end

  # GET /qiwo_categories/1/edit
  def edit
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.find(params[:id])
  end

  # POST /qiwo_categories
  # POST /qiwo_categories.json
  def create
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.new(params[:qiwo_category])

    respond_to do |format|
      if @qiwo_category.save
        format.html { redirect_to @qiwo_category, notice: 'Qiwo category was successfully created.' }
        format.json { render json: @qiwo_category, status: :created, location: @qiwo_category }
      else
        format.html { render action: "new" }
        format.json { render json: @qiwo_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qiwo_categories/1
  # PUT /qiwo_categories/1.json
  def update
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.find(params[:id])

    respond_to do |format|
      if @qiwo_category.update_attributes(params[:qiwo_category])
        format.html { redirect_to @qiwo_category, notice: 'Qiwo category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qiwo_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qiwo_categories/1
  # DELETE /qiwo_categories/1.json
  def destroy
    if session[:activeUser]==nil
        redirect_to "/grant_permission.html"
        return
    end
    @qiwo_category = QiwoCategory.find(params[:id])
    @qiwo_category.destroy

    respond_to do |format|
      format.html { redirect_to qiwo_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qiwo_categories_helper.rb
module QiwoCategoriesHelper
end

app/views/qiwo_categories/_form.html.erb
<%= form_for(@qiwo_category) do |f| %>
  <% if @qiwo_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qiwo_category.errors.count, "error") %> prohibited this qiwo_category from being saved:</h2>

      <ul>
      <% @qiwo_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="field">
    <%= f.label :parent_category %><br />
    <%= f.number_field :parent_category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qiwo_categories/edit.html.erb
<h1>Editing qiwo_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @qiwo_category %> |
<%= link_to 'Back', qiwo_categories_path %>

app/views/qiwo_categories/index.html.erb
    <%= render "shared/topmenu" %>
  <!-- END HEADER -->
  <!-- BEGIN CONTAINER -->
    <div class="clearfix"></div>
  <div class="page-container">
    <!-- BEGIN SIDEBAR -->
     <%= render "shared/leftmenu" %>  
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div class="page-content">
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <%= render "shared/colorsettings" %>
      <!-- BEGIN PAGE CONTAINER-->
        <!-- BEGIN PAGE HEADER-->
        <div class="row">
          <div class="col-md-12">
            <!-- BEGIN STYLE CUSTOMIZER -->
            <h3 class="page-title">
              Mis proveedores <small>Vista general</small>
            </h3>
            <ul class="page-breadcrumb breadcrumb">
              <li>
                <i class="icon-home"></i>
                <a href="index.html">Qiwo</a> 
                <i class="icon-angle-right"></i>
              </li>
              <li><a href="#">Quien me puede surtir</a></li>
              <li class="pull-right">
                     <div id="dashboard-report-range" class="dashboard-date-range tooltips" data-placement="top" data-original-title="Change dashboard date range">
                        <i class="icon-calendar"></i>
                        <span></span>
                        <i class="icon-angle-down"></i>
                     </div>
                  </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
          </div>
        </div>
        
        <div class="row">
                  <div class="col-lg-12 news-blocks">
                        <span>Instrucciones</span>
                        
                        <i class="icon-tags"></i>
                        <p>En esta sección, podrás ver propuestas de todos los proveedores del negocio, a nivel regional y nacional. 
                        Además tienes la certeza de que Qiwo te recomiende estos productos por su nivel de confianza y venta.
                        La prioridad es que esten cerca del negocio, cuenten con disponibilidad y que la venta sea de confianza.
                        </p>
                        
                        <img src="/logo_qiwo_small.png" alt="Qiwo" class="top-news-icon" />
                        
                     </div>
                     </div>


        <!-- END PAGE HEADER-->
        <div>
             <div class="tiles">
             <% 
             alturas=["double-down","","double"]
             colores=["bg-blue","bg-green"]
             @qiwo_providers.each do |singleProvider| %>
             <div class="tile <%= alturas[rand(alturas.length)] %> <%= colores[rand(colores.length)] %>">
               <div class="tile-body">
               <% if singleProvider.image_id_file_name!="" and singleProvider.image_id_file_name!=nil %>
                  <img src="/system/qiwo_products/image_ids/000/000/<% if singleProvider.id<10 %><%= '00' %><% elsif singleProvider.id<100 %><%= '0' %><% end %><%= singleProvider.id %>/medium/<%= singleProvider.image_id_file_name %>" />
                  <% else %>

                  <% end %>
               </div>
               <div class="tile-object">
                  <div class="name">
                     <%= singleProvider.name %>
                  </div>
                  <div class="number">
                     $<%= singleProvider.sale_price %>
                  </div>
               </div>
            </div>
             <% end %>

           
            
            <!-- <div class="tile image selected">
               <div class="tile-body">
                  <img src="assets/img/gallery/image2.jpg" alt="">
               </div>
               <div class="tile-object">
                  <div class="name">
                     Media
                  </div>
               </div>
            </div> -->
            
            
           
         </div>
       
                  </div>
                    
        <!-- end of window -->    
      </div>
      <!-- END PAGE CONTAINER-->    
    
    <!-- END PAGE -->
  </div>
    
  <!-- END CONTAINER -->
  <!-- BEGIN FOOTER -->
<div class="modal fade" id="ajax-edit-product" tabindex="-1" role="basic" aria-hidden="true">
                        <img src="assets/img/ajax-modal-loading.gif" alt="" class="loading">
    </div>
  <div class="footer">
    <div class="footer-inner">
      2014 &copy; Qiwo by Consultware.
    </div>
    <div class="footer-tools">
      <span class="go-top">
      <i class="icon-angle-up"></i>
      </span>
    </div>
  </div>
  

app/views/qiwo_categories/new.html.erb
<h1>New qiwo_category</h1>

<%= render 'form' %>

<%= link_to 'Back', qiwo_categories_path %>

app/views/qiwo_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @qiwo_category.id %>
</p>

<p>
  <b>Category name:</b>
  <%= @qiwo_category.category_name %>
</p>

<p>
  <b>Parent category:</b>
  <%= @qiwo_category.parent_category %>
</p>


<%= link_to 'Edit', edit_qiwo_category_path(@qiwo_category) %> |
<%= link_to 'Back', qiwo_categories_path %>